// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApiDemo.Migrations
{
    [DbContext(typeof(WebAPIDemoContext))]
    [Migration("20260530225046_add_tables")]
    partial class add_tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPIDemo.Models.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KlantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestelling", (string)null);
                });

            modelBuilder.Entity("WebAPIDemo.Models.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Klant", (string)null);
                });

            modelBuilder.Entity("WebAPIDemo.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Prijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RamInGB")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Laptops", (string)null);
                });

            modelBuilder.Entity("WebAPIDemo.Models.OrderLijn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Aantal")
                        .HasColumnType("double precision");

                    b.Property<int>("BestellingId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BestellingId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLijn", (string)null);
                });

            modelBuilder.Entity("WebAPIDemo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschrijving")
                        .HasColumnType("text");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("WebAPIDemo.Models.Bestelling", b =>
                {
                    b.HasOne("WebAPIDemo.Models.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("WebAPIDemo.Models.OrderLijn", b =>
                {
                    b.HasOne("WebAPIDemo.Models.Bestelling", "Bestelling")
                        .WithMany("Orderlijnen")
                        .HasForeignKey("BestellingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPIDemo.Models.Product", "Product")
                        .WithMany("Orderlijnen")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestelling");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebAPIDemo.Models.Bestelling", b =>
                {
                    b.Navigation("Orderlijnen");
                });

            modelBuilder.Entity("WebAPIDemo.Models.Klant", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("WebAPIDemo.Models.Product", b =>
                {
                    b.Navigation("Orderlijnen");
                });
#pragma warning restore 612, 618
        }
    }
}
