// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiDemo.Data;

#nullable disable

namespace WebApiDemo.Migrations
{
    [DbContext(typeof(WebAPIDemoContext))]
    partial class WebAPIDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApiDemo.Models.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KlantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestelling", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KlantId = 1
                        },
                        new
                        {
                            Id = 2,
                            KlantId = 2
                        },
                        new
                        {
                            Id = 3,
                            KlantId = 3
                        },
                        new
                        {
                            Id = 4,
                            KlantId = 2
                        },
                        new
                        {
                            Id = 5,
                            KlantId = 3
                        });
                });

            modelBuilder.Entity("WebApiDemo.Models.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Klant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AangemaaktDatum = new DateTime(2021, 10, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Naam = "Van Der Neffe",
                            Voornaam = "Leon"
                        },
                        new
                        {
                            Id = 2,
                            AangemaaktDatum = new DateTime(2014, 10, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Naam = "Van De Kasseinen",
                            Voornaam = "Firmin"
                        },
                        new
                        {
                            Id = 3,
                            AangemaaktDatum = new DateTime(2023, 10, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Naam = "Kiekeboe",
                            Voornaam = "Marcel"
                        });
                });

            modelBuilder.Entity("WebApiDemo.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Prijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RamInGB")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Laptops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GPU = "Apple M3 Pro 18-core",
                            Merk = "Apple",
                            Prijs = 2499.0,
                            Processor = "M3 Pro",
                            RamInGB = 18
                        },
                        new
                        {
                            Id = 2,
                            GPU = "NVIDIA RTX 4060",
                            Merk = "Dell",
                            Prijs = 1299.99,
                            Processor = "Intel Core i7-13700H",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 3,
                            GPU = "AMD Radeon 780M",
                            Merk = "Lenovo",
                            Prijs = 999.5,
                            Processor = "AMD Ryzen 7 7840HS",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 4,
                            GPU = "NVIDIA RTX 4080",
                            Merk = "ASUS",
                            Prijs = 2199.0,
                            Processor = "Intel Core i9-13900H",
                            RamInGB = 32
                        },
                        new
                        {
                            Id = 5,
                            GPU = "Intel Iris Xe",
                            Merk = "HP",
                            Prijs = 649.0,
                            Processor = "Intel Core i5-1335U",
                            RamInGB = 8
                        },
                        new
                        {
                            Id = 6,
                            GPU = "AMD Radeon 610M",
                            Merk = "Acer",
                            Prijs = 499.0,
                            Processor = "AMD Ryzen 5 7520U",
                            RamInGB = 8
                        },
                        new
                        {
                            Id = 7,
                            GPU = "NVIDIA RTX 4070",
                            Merk = "MSI",
                            Prijs = 1899.99,
                            Processor = "Intel Core i7-14700HX",
                            RamInGB = 32
                        },
                        new
                        {
                            Id = 8,
                            GPU = "Apple M3 10-core",
                            Merk = "Apple",
                            Prijs = 1299.0,
                            Processor = "M3",
                            RamInGB = 8
                        },
                        new
                        {
                            Id = 9,
                            GPU = "Intel Arc Graphics",
                            Merk = "Lenovo",
                            Prijs = 1649.0,
                            Processor = "Intel Core Ultra 7 155H",
                            RamInGB = 32
                        },
                        new
                        {
                            Id = 10,
                            GPU = "NVIDIA RTX 4090",
                            Merk = "ASUS",
                            Prijs = 3299.0,
                            Processor = "AMD Ryzen 9 7945HX",
                            RamInGB = 64
                        },
                        new
                        {
                            Id = 11,
                            GPU = "AMD Radeon Graphics",
                            Merk = "HP",
                            Prijs = 849.0,
                            Processor = "AMD Ryzen 7 7730U",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 12,
                            GPU = "Intel UHD Graphics",
                            Merk = "Dell",
                            Prijs = 579.0,
                            Processor = "Intel Core i5-1235U",
                            RamInGB = 8
                        },
                        new
                        {
                            Id = 13,
                            GPU = "NVIDIA RTX 4090",
                            Merk = "Razer",
                            Prijs = 3599.0,
                            Processor = "Intel Core i9-14900HX",
                            RamInGB = 32
                        },
                        new
                        {
                            Id = 14,
                            GPU = "Intel Arc Graphics",
                            Merk = "Samsung",
                            Prijs = 1199.0,
                            Processor = "Intel Core Ultra 5 125H",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 15,
                            GPU = "Intel Iris Xe",
                            Merk = "Microsoft",
                            Prijs = 1499.0,
                            Processor = "Intel Core i7-1255U",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 16,
                            GPU = "NVIDIA RTX 4050",
                            Merk = "Acer",
                            Prijs = 1099.0,
                            Processor = "Intel Core i7-13620H",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 17,
                            GPU = "NVIDIA RTX 4060",
                            Merk = "Gigabyte",
                            Prijs = 1399.0,
                            Processor = "Intel Core i7-13700H",
                            RamInGB = 16
                        },
                        new
                        {
                            Id = 18,
                            GPU = "Apple M3 Max 30-core",
                            Merk = "Apple",
                            Prijs = 3999.0,
                            Processor = "M3 Max",
                            RamInGB = 36
                        },
                        new
                        {
                            Id = 19,
                            GPU = "AMD Radeon 610M",
                            Merk = "Lenovo",
                            Prijs = 429.0,
                            Processor = "AMD Ryzen 3 7320U",
                            RamInGB = 8
                        },
                        new
                        {
                            Id = 20,
                            GPU = "Intel Arc Graphics",
                            Merk = "HP",
                            Prijs = 1349.0,
                            Processor = "Intel Core Ultra 7 155H",
                            RamInGB = 16
                        });
                });

            modelBuilder.Entity("WebApiDemo.Models.OrderLijn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Aantal")
                        .HasColumnType("double precision");

                    b.Property<int>("BestellingId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BestellingId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLijn", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aantal = 3.0,
                            BestellingId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Aantal = 7.0,
                            BestellingId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Aantal = 4.0,
                            BestellingId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            Aantal = 1.0,
                            BestellingId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            Aantal = 2.0,
                            BestellingId = 3,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 6,
                            Aantal = 3.0,
                            BestellingId = 4,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 7,
                            Aantal = 1.0,
                            BestellingId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 8,
                            Aantal = 2.0,
                            BestellingId = 5,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 9,
                            Aantal = 6.0,
                            BestellingId = 5,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 10,
                            Aantal = 10.0,
                            BestellingId = 5,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("WebApiDemo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschrijving")
                        .HasColumnType("text");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschrijving = "Dit is een fiets",
                            Naam = "fiets",
                            Prijs = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            Beschrijving = "Dit is een mooie koersfiets",
                            Naam = "koersfiets",
                            Prijs = 200.00m
                        },
                        new
                        {
                            Id = 3,
                            Beschrijving = "Dit is een auto",
                            Naam = "auto",
                            Prijs = 2000.00m
                        });
                });

            modelBuilder.Entity("WebApiDemo.Models.Bestelling", b =>
                {
                    b.HasOne("WebApiDemo.Models.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("WebApiDemo.Models.OrderLijn", b =>
                {
                    b.HasOne("WebApiDemo.Models.Bestelling", "Bestelling")
                        .WithMany("OrderLijnen")
                        .HasForeignKey("BestellingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiDemo.Models.Product", "Product")
                        .WithMany("Orderlijnen")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bestelling");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApiDemo.Models.Bestelling", b =>
                {
                    b.Navigation("OrderLijnen");
                });

            modelBuilder.Entity("WebApiDemo.Models.Klant", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("WebApiDemo.Models.Product", b =>
                {
                    b.Navigation("Orderlijnen");
                });
#pragma warning restore 612, 618
        }
    }
}
