// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApiDemo.Data;

#nullable disable

namespace WebApiDemo.Migrations
{
    [DbContext(typeof(WebAPIDemoContext))]
    partial class WebAPIDemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPIDemo.Models.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KlantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestelling", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KlantId = 1
                        },
                        new
                        {
                            Id = 2,
                            KlantId = 2
                        },
                        new
                        {
                            Id = 3,
                            KlantId = 3
                        },
                        new
                        {
                            Id = 4,
                            KlantId = 2
                        },
                        new
                        {
                            Id = 5,
                            KlantId = 3
                        });
                });

            modelBuilder.Entity("WebAPIDemo.Models.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AangemaaktDatum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Klant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AangemaaktDatum = new DateTime(2022, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naam = "Van Der Neffe",
                            Voornaam = "Leon"
                        },
                        new
                        {
                            Id = 2,
                            AangemaaktDatum = new DateTime(2022, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naam = "Van De Kasseinen",
                            Voornaam = "Firmin"
                        },
                        new
                        {
                            Id = 3,
                            AangemaaktDatum = new DateTime(2022, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naam = "Kiekeboe",
                            Voornaam = "Marcel"
                        });
                });

            modelBuilder.Entity("WebAPIDemo.Models.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Prijs")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RamInGB")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Laptops", (string)null);
                });

            modelBuilder.Entity("WebAPIDemo.Models.OrderLijn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Aantal")
                        .HasColumnType("double precision");

                    b.Property<int>("BestellingId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BestellingId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLijn", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aantal = 3.0,
                            BestellingId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Aantal = 7.0,
                            BestellingId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            Aantal = 4.0,
                            BestellingId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            Aantal = 1.0,
                            BestellingId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            Aantal = 2.0,
                            BestellingId = 3,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 6,
                            Aantal = 3.0,
                            BestellingId = 4,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 7,
                            Aantal = 1.0,
                            BestellingId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 8,
                            Aantal = 2.0,
                            BestellingId = 5,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 9,
                            Aantal = 6.0,
                            BestellingId = 5,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 10,
                            Aantal = 10.0,
                            BestellingId = 5,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("WebAPIDemo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschrijving")
                        .HasColumnType("text");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschrijving = "Dit is een fiets",
                            Naam = "fiets",
                            Prijs = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            Beschrijving = "Dit is een mooie koersfiets",
                            Naam = "koersfiets",
                            Prijs = 200.00m
                        },
                        new
                        {
                            Id = 3,
                            Beschrijving = "Dit is een auto",
                            Naam = "auto",
                            Prijs = 2000.00m
                        });
                });

            modelBuilder.Entity("WebAPIDemo.Models.Bestelling", b =>
                {
                    b.HasOne("WebAPIDemo.Models.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("WebAPIDemo.Models.OrderLijn", b =>
                {
                    b.HasOne("WebAPIDemo.Models.Bestelling", "Bestelling")
                        .WithMany("Orderlijnen")
                        .HasForeignKey("BestellingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAPIDemo.Models.Product", "Product")
                        .WithMany("Orderlijnen")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bestelling");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebAPIDemo.Models.Bestelling", b =>
                {
                    b.Navigation("Orderlijnen");
                });

            modelBuilder.Entity("WebAPIDemo.Models.Klant", b =>
                {
                    b.Navigation("Bestellingen");
                });

            modelBuilder.Entity("WebAPIDemo.Models.Product", b =>
                {
                    b.Navigation("Orderlijnen");
                });
#pragma warning restore 612, 618
        }
    }
}
